f=open("file.txt","r")
data = f.read()
print(data)
f.close()
f=open("myfile.txt","w")
f.write("write ing in this file ")
f.write("write ing in this file")
f.close()
f=open("myfile.txt")

data =f.read()
print(data)
f.close()